---
# action.yml
name: 'Hello World'
description: 'An example GitHub Action'
inputs:
  salutation:
    description: 'The greeting to use'
    default: 'Hello'
  subject:
    description: 'The target of the greeting'
    default: 'World'
outputs:
  greeting:
    description: 'The generated greeting'
runs:
  using: 'Docker'
  image: 'docker://gentoo/stage3-amd64:latest'
  args:
  - 'echo'
  - '::set-output name=greeting::${{ inputs.salutation }} ${{ inputs.subject }}'
