---
name: 'Hello World'
on: push
jobs:
  hello:
    name: 'Create Greeting'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Invoke Action'
      uses: 'bencord0/actions-hello@production'
      with:
        salutation: 'Hi'
      id: greeting
    - run: |
        echo "The greeting was: ${{ steps.greeting.outputs.greeting }}"
